# Generated by Django 2.1.3 on 2018-11-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20181113_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorr',
            field=models.CharField(default='temp', max_length=50),
        ),
    ]
