# Generated by Django 2.1.3 on 2018-11-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_authorr'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usernickname',
            field=models.CharField(default='temp', max_length=50),
        ),
    ]
